# SCRIPT DIDACTICO FIREWALL
IPTABLES=/sbin/iptables
EXTIF="enp0s3"
INTIF="enp0s8"
DMZIF="enp0s9"
$IPTABLES -P INPUT ACCEPT
$IPTABLES -F INPUT
$IPTABLES -P OUTPUT ACCEPT
$IPTABLES -F OUTPUT
$IPTABLES -P FORWARD ACCEPT
$IPTABLES -F FORWARD
$IPTABLES -t nat -F
echo "REGLAS LIMPIADAS"
echo "Habilitado el servicio de internet en la Red Interna"
$IPTABLES -t nat -A POSTROUTING -s 25.10.10.0/24 -o $EXTIF -j MASQUERADE
$IPTABLES -t nat -A POSTROUTING -s 20.10.10.0/24 -o $EXTIF -j MASQUERADE
